server:
  port: 9002

jwt:
  secret: secretkey123
spring:
  application:
    name: employee-api

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
